ALTER TABLE projects ADD COLUMN feature_labels BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE projects ADD COLUMN feature_subtasks BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE projects ADD COLUMN feature_dependencies BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE projects ADD COLUMN feature_attachments BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE projects ADD COLUMN feature_comments BOOLEAN NOT NULL DEFAULT FALSE;
